import { Button } from "@arco-design/web-react";

export const formConfigList = [
  [
    { label: "井基本类型", field: "primaryWellType", defaultValue: "" },
    { label: "井名", field: "wellName", defaultValue: "" },
    { label: "井类型", field: "wellType", defaultValue: "" },
    { label: "油田类型", field: "oilFieldName", defaultValue: "" },
    { label: "合同方", field: "contractor", defaultValue: "" },
  ],
  [],
];

const columnMapper = {
  wellName: {
    fixed: "left",
  },
  company: {
    fixed: "left",
  },
  操作: {
    width: 200,
    fixed: "right",
    render: () => (
      <Button type="primary" status="danger" size="mini">
        删除
      </Button>
    ),
  },
};

export const columns = [
  "wellName",
  "company",
  "primaryWellType",
  "wellType",
  "startTime",
  "endTime",
  "durationHours",
  "firstLevelCode",
  "secondLevelCode",
  "thirdLevelCode",
  "fourthLevelCode",
  "complexityType",
  "wellSection",
  "startDepth",
  "endDepth",
  "operationDescription",
  "status",
  "onlyKey",
  "drillBitNumber",
  "drillBitType",
  "sizeIn",
  "manufacturer",
  "model",
  "serialNumber",
  "nozzleSize",
  "drillBitTFAn2",
  "entryDepth",
  "exitDepth",
  "entryTime",
  "exitTime",
  "advanceDistance",
  "pureDrillingTime",
  "rop",
  "maxDrillingPressure",
  "minDrillingPressure",
  "maxRotationSpeed",
  "minRotationSpeed",
  "iadcWearEvaluation",
  "encounteredFormation",
  "holeDiameter",
  "steelGrade",
  "yieldValue",
  "casingLength",
  "casingDiameter",
  "casingSetDepth",
  "upperCasingDiameter",
  "startVerticalDepth",
  "cementReturnHeight",
  "plasticViscosity",
  "drillingFluidDensity",
  "upperCasingSetDepth",
  "drillingFluidSystem",
  "endVerticalDepth",
  "formationPressure",
  "oilFieldName",
  "oilFieldCode",
  "isCooperative",
  "contractor",
  "secondaryWellType",
  "tertiaryWellType",
  "waterDepth1",
  "designDepth",
  "designVerticalDepth",
  "designDate",
  "structureName",
  "uniqueWellId",
  "chineseWellName",
  "operator",
  "hydrocarbonType",
  "riskLevel",
  "riskType",
  "riskGrade",
  "sulfurGrade",
  "containsCO2",
  "zeroDepth",
  "initialKellyElevation",
  "groundElevation",
  "currentKellyElevation",
  "casingHeadElevation",
  "waterDepth2",
  "mudLineElevation",
  "artificialBottomDepth",
  "drillingDays",
  "positioningMethod",
  "location",
  "geodeticSystem",
  "longitude",
  "latitude",
  "xcoordinate",
  "ycoordinate",
  "slotNumber",
  "country",
  "region",
  "province",
  "county",
  "scrapedWell",
  "officePhone",
  "操作",
].map((str) => {
  return {
    key: str,
    title: str,
    dataIndex: str,
    width: str.length * 12,
    ...(columnMapper[str] ?? {}),
  };
});
