petroleum:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: your-database-host
    port: 3306
    database: petroleum-data-storage
    username: your-database-username
    password: your-database-password
minio:
  access-key: yU5bJmvaJ8WweyCK1eI6
  secret-key: pYKeZhxkuMvUlA7o2LUnEmVzWHQrmqc6WKXE77BU
  bucket-name: eraserbucket
  endpoint:

