petroleum:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: your-database-host
    port: 3306
    database: petroleum-data-storage
    username: your-database-username
    password: your-database-password

