package com.petroleumpojo.entity;


import lombok.Data;

@Data
public class DataLake {
    private Float SPR3;           
    private Float TVA;            
    private Float DATA3;          
    private String GUID;          
    private Float MTOA;           
    private String DATE_TIME_INDEX; 
    private Float SPR5;           
    private Float LSTK;           
    private String WID;           
    private Float DATA11;         
    private Float HKLA;           
    private String collect_job_id; 
    private Float WOBX;           
    private String MONTH;         
    private Float TQX;            
    private Float DATA4;          
    private Float DATA15;         
    private Float MFIA;           
    private String DATE;          
    private Float SPR4;           
    private Float STKC;           
    private Float ROPA;           
    private String is_submit_centre_db; 
    private String data_asset_code; 
    private String delete_flag;   
    private String archive_flag;  
    private String dataset_class; 
    private String update_date;   
    private String update_user;   
    private String update_org;    
    private String quality_tag;   
    private String branch_id;     
    private String acqtn_mode;    
    private Float SPPA;           
    private String verify_date;   
    private String verifier;      
    private String verify_org;    
    private String secrecy_level; 
    private String input_time;    
    private String input_user;    
    private String input_org;     
    private String uniontime;     
    private String publish_org;   
    private Float GASA;           
    private Float DATA10;         
    private Float SPM3;           
    private Float DRTM;           
    private Float DBTV;           
    private String SKNO;          
    private Float TVCA;           
    private Float SPR1;           
    private Float MFOP;           
    private Float MDOA;           
    private Float CHKP;           
    private Float MTIA;           
    private Float TQA;            
    private Float HKLX;           
    private Float MCIA;           
    private Float DATA14;         
    private Float DATA9;          
    private Float DATA1;          
    private Float SPM1;           
    private String SEQID;         
    private String ACTC;          
    private Long TIME;            
    private Float SPM4;           
    private Float DMEA;           
    private Float SPM2;           
    private Float DATA13;         
    private Float SPR2;           
    private Float WOBA;           
    private Float DVER;           
    private Float MDIA;           
    private Float DATA12;         
    private Float DATA8;          
    private Short RID;            
    private Float DATA6;          
    private Float DATA2;          
    private Float MFOA;           
    private Float BPOS;           
    private String ACTC2;         
    private Float RPMA;           
    private Float DATA5;          
    private Float DBTM;           
    private Float DATA7;          
    private Float MCOA;           
}

