name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
          package_json_file: web/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: cd web && pnpm i

      - name: Build the application
        run: cd web && pnpm run build
        env:
          CI: false # 避免在生产模式下执行额外的检查

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
